[[contracts]]
fqn = "sooth_contracts::Susd"

[[contracts]]
fqn = "sooth_contracts::BinaryMarket"

[[contracts]]
fqn = "sooth_contracts::MarketFactory"

[[contracts]]
fqn = "sooth_contracts::BinaryMarketFactory"
